import React, { useState } from 'react';
import { Box, Typography, Alert, Button } from '@mui/material';
import StudentForm from './StudentForm';
import { Gender } from '../../../../types/user';
import type { StudentFormData } from '../../../../types/forms';

export const StudentFormTest: React.FC = () => {
  const [result, setResult] = useState<string>('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (data: StudentFormData) => {
    setLoading(true);
    setResult('');
    
    try {
      console.log('StudentForm submission data:', data);
      
      // Simulate API call
      const response = await fetch('http://localhost:8080/api/v1/students', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('authToken') || 'test-token'}`
        },
        body: JSON.stringify(data)
      });

      if (response.ok) {
        const responseData = await response.json();
        setResult(`✅ SUCCESS: Student created with ID: ${responseData.id}, Roll Number: ${responseData.rollNumber}`);
      } else {
        const errorText = await response.text();
        setResult(`❌ ERROR: ${response.status} - ${errorText}`);
      }
    } catch (error) {
      setResult(`❌ ERROR: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setResult('Form cancelled');
  };

  const clearResult = () => {
    setResult('');
  };

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h5" gutterBottom>
        Student Form Test
      </Typography>
      
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Test the StudentForm component with backend integration. 
        The form has been updated to match backend requirements:
        • Roll number is auto-generated by backend
        • Gender uses numeric enum values (0=Male, 1=Female, 2=Other)
        • Date fields are converted to DateTime format
        • isActive field removed (handled by backend)
      </Typography>

      {result && (
        <Alert 
          severity={result.includes('SUCCESS') ? 'success' : 'error'} 
          sx={{ mb: 2 }}
          action={
            <Button color="inherit" size="small" onClick={clearResult}>
              Clear
            </Button>
          }
        >
          {result}
        </Alert>
      )}

      <StudentForm
        onSubmit={handleSubmit}
        onCancel={handleCancel}
        loading={loading}
        submitText="Create Student"
        initialData={{
          firstName: 'John',
          lastName: 'Doe',
          email: 'john.doe@student.example.com',
          phoneNumber: '+1234567890',
          dateOfBirth: '2005-01-15',
          address: '123 Student Street, College Town',
          gender: Gender.MALE,
          enrollmentDate: '2023-09-01',
          grade: '10',
          section: 'A',
          parentId: '',
          facultyIds: []
        }}
      />
    </Box>
  );
};