import React, { useState } from 'react';
import { Box, Typography, Alert } from '@mui/material';
import FacultyForm from './FacultyForm';
import { Gender } from '../../../../types/user';
import type { FacultyFormData } from '../../../../types/forms';

const FacultyFormTest: React.FC = () => {
    const [submittedData, setSubmittedData] = useState<FacultyFormData | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleSubmit = async (data: FacultyFormData) => {
        try {
            console.log('Form submitted with data:', data);
            
            // Verify that employeeId and isActive are not in the data
            if ('employeeId' in data) {
                throw new Error('employeeId should not be present in form data');
            }
            if ('isActive' in data) {
                throw new Error('isActive should not be present in form data');
            }
            
            // Verify that dates are converted to Date objects
            if (typeof (data as any).dateOfBirth !== 'object' || !((data as any).dateOfBirth instanceof Date)) {
                throw new Error('dateOfBirth should be converted to Date object');
            }
            if (typeof (data as any).hireDate !== 'object' || !((data as any).hireDate instanceof Date)) {
                throw new Error('hireDate should be converted to Date object');
            }
            
            setSubmittedData(data);
            setError(null);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Unknown error');
            setSubmittedData(null);
        }
    };

    const handleCancel = () => {
        console.log('Form cancelled');
        setSubmittedData(null);
        setError(null);
    };

    const initialData: FacultyFormData = {
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '+1234567890',
        dateOfBirth: '1985-06-15',
        address: '123 Main Street, City, State 12345',
        gender: Gender.MALE,
        department: 'Computer Science',
        subject: 'Software Engineering',
        hireDate: '2020-08-01',
        userId: 'user123',
    };

    return (
        <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
            <Typography variant="h4" gutterBottom>
                Faculty Form Test
            </Typography>
            
            <Typography variant="body1" sx={{ mb: 3 }}>
                This test verifies that the FacultyForm component:
                <ul>
                    <li>✅ Removed employeeId field (auto-generated by backend)</li>
                    <li>✅ Removed isActive field (handled by backend)</li>
                    <li>✅ Added optional userId field for linking to user accounts</li>
                    <li>✅ Converts date strings to DateTime objects for backend</li>
                    <li>✅ Fixed TypeScript resolver issues</li>
                </ul>
            </Typography>

            <FacultyForm
                initialData={initialData}
                onSubmit={handleSubmit}
                onCancel={handleCancel}
                mode="edit"
                testId="faculty-form-test"
            />

            {error && (
                <Alert severity="error" sx={{ mt: 3 }}>
                    <Typography variant="h6">Test Failed:</Typography>
                    {error}
                </Alert>
            )}

            {submittedData && (
                <Alert severity="success" sx={{ mt: 3 }}>
                    <Typography variant="h6">Test Passed! ✅</Typography>
                    <Typography variant="body2" component="pre" sx={{ mt: 1, fontSize: '0.8rem' }}>
                        {JSON.stringify(submittedData, null, 2)}
                    </Typography>
                </Alert>
            )}
        </Box>
    );
};

export default FacultyFormTest;